# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[('core', 'core'), ('modules', 'modules'), ('framework', 'framework'), ('gui', 'gui'), ('assets', 'assets')],
    hiddenimports=[
        # python-docx
        'docx', 'docx.enum.table', 'docx.enum.text', 'docx.oxml', 'docx.oxml.ns', 'docx.shared',
        # openpyxl
        'openpyxl', 'openpyxl.drawing.image', 'openpyxl.styles', 'openpyxl.utils',
        # PIL / Pillow
        'PIL', 'PIL.Image', 'PIL.ImageTk', 'PIL.ImageDraw', 'PIL.ImageFont', 'PIL.ExifTags',
        # reportlab
        'reportlab', 'reportlab.lib', 'reportlab.lib.colors', 'reportlab.lib.pagesizes',
        'reportlab.lib.styles', 'reportlab.lib.units', 'reportlab.lib.enums', 'reportlab.lib.fonts',
        'reportlab.platypus', 'reportlab.pdfgen', 'reportlab.pdfbase', 'reportlab.pdfbase.pdfmetrics',
        'reportlab.pdfbase.ttfonts',
        # matplotlib
        'matplotlib', 'matplotlib.figure', 'matplotlib.backends.backend_tkagg', 'matplotlib.ticker',
        # tkcalendar + babel
        'tkcalendar', 'babel.numbers',
        # tkinter submodules
        'tkinter.colorchooser', 'tkinter.filedialog', 'tkinter.messagebox', 'tkinter.ttk',
        # stdlib
        'sqlite3', 'mailbox', 'csv', 'configparser', 'ctypes', 'email', 'hashlib',
        'json', 'queue', 'uuid', 'getpass',
        # misc third-party
        'pypdf', 'pdfplumber', 'pdfminer', 'pdfminer.high_level', 'send2trash',
        # migrations (dynamically discovered — must be listed explicitly)
        'core.migrations.versions.v0001_baseline',
        'core.migrations.versions.v0002_candidate_signature_fields',
        'core.migrations.versions.v0003_crm_relationship_integrity',
        'core.migrations.versions.v0004_crm_numbering_and_sites',
        'core.migrations.versions.v0005_business_settings',
        'core.migrations.versions.v0006_picklists',
        'core.migrations.versions.v0007_quotes',
        'core.migrations.versions.v0008_quote_number_per_customer',
        'core.migrations.versions.v0009_line_item_type_picklist',
        'core.migrations.versions.v0010_quote_documents_and_statements',
        'core.migrations.versions.v0011_maintenance_line_item_types',
        'core.migrations.versions.v0012_purchase_order_number',
        'core.migrations.versions.v0013_quote_revisions',
        'core.migrations.versions.v0014_quote_vat_number',
        'core.migrations.versions.v0015_line_item_colour_and_additional_height',
        'core.migrations.versions.v0016_new_net_line_item_types',
        'core.migrations.versions.v0017_documents',
        'core.migrations.versions.v0018_payments',
        'core.migrations.versions.v0019_ledger_transactions',
        'core.migrations.versions.v0020_ledger_categories_audit_receipts',
        'core.migrations.versions.v0021_category_rewording_and_additions',
        'core.migrations.versions.v0022_customer_registration_number',
        'core.migrations.versions.v0023_quote_bill_to_name',
        'core.migrations.versions.v0024_site_visits',
        'core.migrations.versions.v0025_client_folders_and_warranty',
        'core.migrations.versions.v0026_site_images',
        'core.migrations.versions.v0027_site_plans',
        'core.migrations.versions.v0028_site_plan_item_car_bays',
        'core.migrations.versions.v0029_job_cards',
        'core.migrations.versions.v0030_crm_soft_delete',
        'core.migrations.versions.v0031_supplier_pricing',
        'core.migrations.versions.v0032_ledger_category_rules',
        'core.migrations.versions.v0033_anchor_pole_76mm',
        'core.migrations.versions.v0034_supplier_pricing_vat_basis',
        'core.migrations.versions.v0035_correct_flatbar_and_angle_prices',
        'core.migrations.versions.v0036_site_plan_item_rotation',
        'core.migrations.versions.v0037_site_plan_grid_orientation',
        'core.migrations.versions.v0038_rename_standard_to_four_post',
        'core.migrations.versions.v0039_purge_orphaned_child_rows',
        'core.migrations.versions.v0040_balance_sheet_accounts',
        'core.migrations.versions.v0041_proposals',
        'core.migrations.versions.v0042_site_visit_measurements',
        'core.migrations.versions.v0043_site_image_tags_album',
        'core.migrations.versions.v0044_scheduled_jobs',
        'core.migrations.versions.v0045_site_image_hash_size',
        'core.migrations.versions.v0046_quote_accepted_date',
        'core.migrations.versions.v0047_job_cost_items',
        'core.migrations.versions.v0048_fix_account_labels_and_categories',
        'core.migrations.versions.v0049_bank_accounts_table',
        'core.migrations.versions.v0050_bank_accounts_noop',
        'core.migrations.versions.v0051_annual_compliance',
        'core.migrations.versions.v0052_site_plan_net_measurements',
        'core.migrations.versions.v0053_picklist_category',
        'core.migrations.versions.v0054_quote_print_address_flags',
        'core.migrations.versions.v0055_job_cost_allocations',
        # modules (collected via collect_submodules in hookspath is preferred, but list explicitly as fallback)
        'modules.job_costing', 'modules.job_costing.module', 'modules.job_costing.utility', 'modules.job_costing.windows',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Ops Hub',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets\\ops_hub.ico'],
)
